# Generated by Django 5.1 on 2024-08-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Phone_number', models.CharField(max_length=300)),
                ('mail', models.EmailField(max_length=300)),
                ('Password', models.CharField(max_length=300)),
                ('confirm_password', models.CharField(max_length=300)),
            ],
        ),
    ]
